### ISSUE TITLE
using two addons

### ISSUE THREAD

**Issue by ryankicks** [TeleSign/python_telesign#12]
For the Python example, I'm trying to use two addons with `phoneid()`, but it doesn't seem to be working. My code does the following:

`response = phoneid.phoneid(phone_number, ucid, addons={'number_deactivation': {}, 'contact': {}})`

When I execute, I only get `number_deactivation` back. When I only use `contact`, it will return contact information. When I only use `number_deactivation`, it will return number_deactivation information.

I wonder if it's related to this code in `rest.py`:

```
        if method_name in ['POST', 'PUT']:
            payload = {'data': url_encoded_fields}
        else:
            payload = {'params': url_encoded_fields}
```

I wonder if it's because it flattens the structure in the payload/API call, as such:

`{u'data': 'addons=contact&addons=number_deactivation&ucid=ATCK'}`

When I use CURL, passing two parameters works, as such:

`curl --request POST https://rest-ww.telesign.com/v1/phoneid/SOMENUMBER --header "Content-Type: application/json" --data '{"addons":{"number_deactivation":{},"contact":{}}}' --user "TOKEN":"KEY"`

**Comment by bshen-telesign** [comment]
This was because our SDK didn't support json payloads prior to release 2.2.2, thus causing the flattening you're seeing. Try upgrading to 2.2.2, and this issue should be fixed.

**Comment by bshen-telesign** [comment]
I meant the telesign package (i.e. the source of which is this repository). That was the correct version.

As a side note, only the telesign package provides functionality for addons; the telesignenterprise package does not support them.

**Comment by ryankicks** [comment]
Thanks. When I started, I was told to use telesignenterprise. Do I not need to anymore?

**Comment by bshen-telesign** [comment]
You don't need telesignenterprise for phoneid with number_deactivation and contact addons. However, some of our other products are only available with our enterprise SDK, so if you guys are integrating any of those (primarily app verify, sms verify, voice verify), you will still need the telesignenterprise package.

I'm not sure, but I believe you were told to use telesignenterprise mostly so that you guys are directed to our enterprise load balancers, which are managed differently. You'll see this difference in `telesignenterprise.PhoneIdClient.__init__`'s default `rest_endpoint` kwarg.

If this is the case, you can simply pass `rest_endpoint='https://rest-ww.telesign.com'` to the non-enterprise `telesign.PhoneIdClient` constructor call after your `customer_id` and `api_key`.

I'll double check with our CS and get back to you (or maybe they will).

**Comment by bshen-telesign** [comment]
So I've checked with a couple people:
- As long as you're not importing from `telesignenterprise` directly for some of our other products, then you don't need to have that package installed.
- However, you *should* pass `rest_endpoint='https://rest-ww.telesign.com'` to `telesign.PhoneIdClient(customer_id, api_key, rest_endpoint=...)` so that you guys are directed to that specific load balancer.
