### ISSUE TITLE
How to send video mms?

### ISSUE THREAD

**Issue by virajkanwade** [TeleSign/python_telesign#20]

**Comment by adohertyTS** [comment]
Hi @virajkanwade ! Our SDKs do not support sending video with MMS. I'm guessing since you are raising this issue on our self-service Python SDK repo that you have a self-service account. If you upgrade to a full-service account, you can use the Messaging product on our Engage API to send video with MMS. See https://developer.telesign.com/enterprise/docs/messaging-send-media-with-mms for more details about how you would use that API for this use case.

**Comment by virajkanwade** [comment]
@adohertyTS Thats for the response. One thing I am still not sure, what is self-service vs full-service account?

I signed up for a trial. Now when I click on Upgrade, it asks me to add funds to the account with minimum $20. Will that make it into full-service account?

**Comment by virajkanwade** [comment]
I found this which tells you what type of account you are on. But still not clear how to signup for a new account on trial basis for a POC?

**Comment by adohertyTS** [comment]
@virajkanwade self-service accounts are the ones you sign up for yourself on our website, and give you access to a limited set of our products. To open a full-service account, you'll have to talk to our sales team. You can submit a request for that here: https://www.telesign.com/contact-sales. Is there anything else I can help you with?

**Comment by virajkanwade** [comment]
Thanks @adohertyTS . I had previously submitted a request and again submitted one. The success message said I should hear back in 1 business day. But I haven't heard back yet. Anyways. Thanks
